---
- name: Install apt packages
  tags: common
  become: true
  apt:
    name:
      # essential build tools (gcc, make, etc)
      - build-essential
      - libtool
      - python
      - python3
      - pkg-config

      # Needed for mounting recovery image
      - kpartx

      # Audio / CRAS dependencies
      - acpid
      - libudev-dev
      - libsbc-dev
      - libalsaplayer-dev
      - libiniparser-dev
      - ladspa-sdk
      - libspeex-dev
      - libspeexdsp-dev
      - libasound2-dev
    state: latest
